-- Seed data for German Bachelor programs (MVP)
-- Tags use the same vocabulary as the quiz answers

INSERT INTO programs (name, field, degree, duration_semesters, language, nc_required, nc_grade, description, career, interests, strengths, work_style, tuition_per_semester, is_stem, is_business, is_social, is_creative, is_health, popularity_rank) VALUES
-- STEM
('Informatik', 'Technik & IT', 'Bachelor', 6, 'de', 1, 2.5, 'Entwicklung von Software, Algorithmen, Datenbanken und IT-Systemen.','Softwareentwickler, IT-Berater, Data Engineer, Produktmanager', '["technik","logik","digitales","mathematik"]','["mathematik","informatik","physik"]','["analytisch","problemloesend","selbstaendig"]',0,1,0,0,0,0,1),
('Data Science', 'Technik & IT', 'Bachelor', 6, 'de', 1, 2.3, 'Analyse großer Datenmengen mit Statistik, Programmierung und Machine Learning.','Data Scientist, Analyst, KI-Spezialist, Berater', '["technik","logik","mathematik","wirtschaft"]','["mathematik","informatik","englisch"]','["analytisch","strukturiert","teamfaehig"]',0,1,0,0,0,0,5),
('Maschinenbau', 'Ingenieurwesen', 'Bachelor', 6, 'de', 1, 2.7, 'Konstruktion, Entwicklung und Fertigung von Maschinen und Anlagen.','Konstrukteur, Projektingenieur, F&E, Produktionsleiter', '["technik","fahrzeuge","energie","handwerk"]','["mathematik","physik","technik"]','["praktisch","analytisch","teamfaehig"]',0,1,0,0,0,0,2),
('Elektrotechnik', 'Ingenieurwesen', 'Bachelor', 6, 'de', 1, 2.8, 'Entwicklung elektrischer und elektronischer Systeme, von Chips bis erneuerbare Energien.','Elektroingenieur, Embedded-Entwickler, Energieberater', '["technik","energie","digitales","forschung"]','["physik","mathematik","informatik"]','["analytisch","praktisch","praezise"]',0,1,0,0,0,0,8),
('Bauingenieurwesen', 'Ingenieurwesen', 'Bachelor', 6, 'de', 1, 2.9, 'Planung, Berechnung und Bau von Gebäuden, Brücken und Infrastruktur.','Bauingenieur, Bauleiter, Projektsteuerer', '["technik","architektur","umwelt","handwerk"]','["mathematik","physik","technik"]','["praktisch","teamfaehig","verantwortungsbewusst"]',0,1,0,0,0,0,12),
('Physik', 'Naturwissenschaften', 'Bachelor', 6, 'de', 0, NULL, 'Grundlagen der Naturgesetze, Experimente, theoretische Modellbildung.','Forscher, Datenanalyst, Patentprüfer, Lehrer', '["forschung","weltraum","technik","mathematik"]','["physik","mathematik","chemie"]','["analytisch","theoretisch","neugierig"]',0,1,0,0,0,0,20),
('Chemie', 'Naturwissenschaften', 'Bachelor', 6, 'de', 0, NULL, 'Aufbau der Materie, chemische Reaktionen, Laborarbeit.','Chemiker, Pharmaberater, Labormanager, Qualitätssicherung', '["forschung","medizin","umwelt","labor"]','["chemie","mathematik","biologie"]','["praezise","experimentell","geduldig"]',0,1,0,0,0,0,25),
('Biologie', 'Naturwissenschaften', 'Bachelor', 6, 'de', 0, NULL, 'Lebenswissenschaften von der Zelle bis zum Ökosystem.','Biologe, Forscher, Umweltberater, Pharma', '["natur","tiere","pflanzen","forschung","medizin"]','["biologie","chemie","mathematik"]','["beobachtend","experimentell","detailorientiert"]',0,1,0,0,0,0,18),
('Mathematik', 'Naturwissenschaften', 'Bachelor', 6, 'de', 0, NULL, 'Abstrakte Strukturen, Beweise, Modellierung komplexer Probleme.','Data Scientist, Berater, Risikoanalyst, Lehrer', '["logik","mathematik","forschung","finanzen"]','["mathematik","physik","informatik"]','["analytisch","abstrakt","geduldig"]',0,1,0,0,0,0,30),
('Geoinformatik', 'Technik & IT', 'Bachelor', 6, 'de', 1, 2.6, 'Digitale Erfassung, Analyse und Darstellung räumlicher Daten.','GIS-Spezialist, Stadtplaner, Umweltberater', '["technik","umwelt","kartografie","logik"]','["mathematik","informatik","geografie"]','["analytisch","visuell","strukturiert"]',0,1,0,0,0,0,45),

-- Business
('BWL', 'Wirtschaft', 'Bachelor', 6, 'de', 1, 2.2, 'Betriebswirtschaftslehre: Finanzen, Marketing, Personal, Strategie.','Consultant, Banker, Controller, Marketingmanager', '["wirtschaft","management","finanzen","unternehmertum"]','["mathematik","deutsch","englisch"]','["kommunikativ","strategisch","zielorientiert"]',0,0,1,0,0,0,3),
('Wirtschaftsinformatik', 'Wirtschaft', 'Bachelor', 6, 'de', 1, 2.4, 'Brücke zwischen Wirtschaft und IT: Prozesse, Systeme, Digitalisierung.','IT-Berater, Projektmanager, Business Analyst', '["technik","wirtschaft","digitales","management"]','["mathematik","informatik","englisch"]','["analytisch","kommunikativ","loesungsorientiert"]',0,1,1,0,0,0,6),
('Volkswirtschaftslehre', 'Wirtschaft', 'Bachelor', 6, 'de', 0, NULL, 'Makroökonomie, Mikroökonomie, Politikberatung und ökonomische Theorie.','Volkswirt, Policy Analyst, Wirtschaftsjournalist', '["wirtschaft","politik","gesellschaft","forschung"]','["mathematik","englisch","deutsch"]','["analytisch","theoretisch","gesellschaftlich"]',0,0,1,0,0,0,22),
('International Business', 'Wirtschaft', 'Bachelor', 6, 'en', 1, 2.3, 'Internationales Management, interkulturelle Kommunikation, globale Märkte.','Exportmanager, Berater, internationaler Projektmanager', '["wirtschaft","reisen","kultur","management"]','["englisch","mathematik","deutsch"]','["kommunikativ","mobil","offen"]',0,0,1,0,0,0,15),
('Marketingmanagement', 'Wirtschaft', 'Bachelor', 6, 'de', 1, 2.5, 'Markenführung, Werbung, digitales Marketing, Konsumentenverhalten.','Marketingmanager, Social Media Manager, Marktforscher', '["kreativ","wirtschaft","medien","kommunikation"]','["deutsch","englisch","kunst"]','["kreativ","kommunikativ","trendbewusst"]',0,0,1,0,1,0,28),
('Industrial Engineering', 'Wirtschaft', 'Bachelor', 6, 'de', 1, 2.6, 'Kombination aus Technik und Betriebswirtschaft für Produktion und Logistik.','Produktionsplaner, Supply-Chain-Manager, Berater', '["technik","wirtschaft","management","logistik"]','["mathematik","physik","informatik"]','["analytisch","praktisch","organisiert"]',0,1,1,0,0,0,19),

-- Health
('Medizin', 'Medizin & Gesundheit', 'Bachelor', 12, 'de', 1, 1.0, 'Humanmedizin: Krankheitslehre, Klinik, Patientenversorgung.','Arzt, Chirurg, Hausarzt, Forscher', '["medizin","mensch","biologie","forschung"]','["biologie","chemie","mathematik"]','["empathisch","belastbar","praezise"]',0,1,0,0,0,1,4),
('Zahnmedizin', 'Medizin & Gesundheit', 'Bachelor', 10, 'de', 1, 1.1, 'Zahnerhaltung, Kieferorthopädie, Mundgesundheit.','Zahnarzt, Kieferorthopäde', '["medizin","handwerk","mensch","gesundheit"]','["biologie","chemie","kunst"]','["manuell-geschickt","empathisch","praezise"]',0,1,0,0,0,1,17),
('Psychologie', 'Medizin & Gesundheit', 'Bachelor', 6, 'de', 1, 1.3, 'Wissenschaft vom Verhalten, Denken und Erleben des Menschen.','Psychologe, Berater, HR, Marktforscher', '["mensch","verhalten","forschung","gesundheit"]','["biologie","deutsch","mathematik"]','["empathisch","analytisch","zuhoerend"]',0,0,0,1,0,1,7),
('Pflegewissenschaft', 'Medizin & Gesundheit', 'Bachelor', 6, 'de', 0, NULL, 'Wissenschaftliche Fundierung von Pflege, Management und Gesundheitsförderung.','Pflegedienstleitung, Gesundheitsmanager, Berater', '["mensch","gesundheit","pflege","management"]','["biologie","deutsch","sozialkunde"]','["empathisch","organisiert","belastbar"]',0,0,0,1,0,1,35),
('Molekulare Biomedizin', 'Medizin & Gesundheit', 'Bachelor', 6, 'de', 1, 1.5, 'Grundlagenforschung für Medizin: Zellbiologie, Genetik, Krankheitsmechanismen.','Forscher, Pharma, Laborleiter', '["forschung","medizin","biologie","labor"]','["biologie","chemie","mathematik"]','["experimentell","analytisch","geduldig"]',0,1,0,0,0,1,40),
('Ernährungswissenschaft', 'Medizin & Gesundheit', 'Bachelor', 6, 'de', 0, NULL, 'Zusammenhang zwischen Ernährung, Gesundheit und Krankheit.','Ernährungsberater, Lebensmittelindustrie, Forscher', '["gesundheit","ernaehrung","biologie","mensch"]','["biologie","chemie","deutsch"]','["beratend","gesundheitsorientiert","kommunikativ"]',0,1,0,0,0,1,50),

-- Social & Law
('Rechtswissenschaft', 'Recht', 'Bachelor', 8, 'de', 1, 1.7, 'Gesetze, Verträge, Rechtsprechung, Staatsrecht.','Rechtsanwalt, Richter, Unternehmensjurist', '["recht","gesellschaft","politik","logik"]','["deutsch","geschichte","englisch"]','["analytisch","sprachgewandt","konfliktfaehig"]',0,0,0,1,0,0,9),
('Soziale Arbeit', 'Soziales', 'Bachelor', 6, 'de', 0, NULL, 'Unterstützung benachteiligter Menschen, Jugendhilfe, Beratung.','Sozialarbeiter, Jugendhilfe, Beratung', '["mensch","sozial","gerechtigkeit","beratung"]','["deutsch","sozialkunde","biologie"]','["empathisch","praktisch","kommunikativ"]',0,0,0,1,0,0,23),
('Politikwissenschaft', 'Soziales', 'Bachelor', 6, 'de', 0, NULL, 'Analyse politischer Systeme, Macht, internationale Beziehungen.','Politikberater, Lobbyist, Journalist, Verwaltung', '["politik","gesellschaft","international","forschung"]','["geschichte","deutsch","englisch"]','["analytisch","diskursiv","gesellschaftlich"]',0,0,0,1,0,0,24),
('Soziologie', 'Soziales', 'Bachelor', 6, 'de', 0, NULL, 'Gesellschaftliche Strukturen, Gruppenverhalten, soziale Ungleichheit.','Markt- und Sozialforscher, Berater, Journalist', '["gesellschaft","mensch","forschung","kultur"]','["deutsch","mathematik","geschichte"]','["beobachtend","analytisch","kritisch"]',0,0,0,1,0,0,38),
('Pädagogik', 'Soziales', 'Bachelor', 6, 'de', 0, NULL, 'Bildungsprozesse, Didaktik, Erwachsenenbildung.','Bildungsmanager, Trainer, Berater, Verwaltung', '["mensch","bildung","beratung","gesellschaft"]','["deutsch","englisch","kunst"]','["kommunikativ","strukturiert","geduldig"]',0,0,0,1,0,0,36),

-- Creative & Media
('Kommunikationswissenschaft', 'Medien', 'Bachelor', 6, 'de', 0, NULL, 'Massenmedien, Journalismus, Public Relations, Medienwirkung.','Journalist, PR-Manager, Kommunikationsberater', '["medien","kommunikation","gesellschaft","kultur"]','["deutsch","englisch","geschichte"]','["kommunikativ","recherchefreudig","textgewandt"]',0,0,0,0,1,0,21),
('Journalismus', 'Medien', 'Bachelor', 6, 'de', 1, 2.0, 'Recherche, Texten, Multimedia, Redaktion für verschiedene Kanäle.','Journalist, Redakteur, Content Manager', '["medien","kommunikation","politik","kultur"]','["deutsch","englisch","geschichte"]','["neugierig","textgewandt","belastbar"]',0,0,0,0,1,0,26),
('Mediendesign', 'Design', 'Bachelor', 6, 'de', 1, 2.4, 'Gestaltung digitaler Medien: UI/UX, Motion, Web, Branding.','Art Director, UI/UX-Designer, Motion Designer', '["design","technik","medien","kreativ"]','["kunst","informatik","englisch"]','["kreativ","visuell","detailorientiert"]',0,0,0,0,1,0,27),
('Architektur', 'Design', 'Bachelor', 8, 'de', 1, 2.3, 'Entwurf von Gebäuden, Stadtplanung, Baugeschichte und Konstruktion.','Architekt, Stadtplaner, Projektleiter', '["architektur","design","technik","kunst"]','["mathematik","kunst","physik"]','["kreativ","technisch","praesezentationsstark"]',0,1,0,0,1,0,14),
('Produktdesign', 'Design', 'Bachelor', 6, 'de', 1, 2.5, 'Gestaltung von Gebrauchsgegenständen, von der Idee bis zur Fertigung.','Produktdesigner, UX-Designer, Modellbauer', '["design","handwerk","technik","kreativ"]','["kunst","mathematik","physik"]','["kreativ","praktisch","nutzerorientiert"]',0,0,0,0,1,0,33),
('Mode- und Textildesign', 'Design', 'Bachelor', 6, 'de', 1, 2.7, 'Modekonzeption, Schnitttechnik, Materialkunde, Nachhaltigkeit.','Modeschöpfer, Textilingenieur, Stylist', '["mode","design","kunst","handwerk"]','["kunst","textil","englisch"]','["kreativ","handwerklich","trendbewusst"]',0,0,0,0,1,0,55),

-- Languages & Culture
('Anglistik / Englisch', 'Sprachen', 'Bachelor', 6, 'de/en', 0, NULL, 'Englische Sprache, Literatur und Kultur.','Lehrer, Übersetzer, Redakteur, Berater', '["sprachen","kultur","literatur","reisen"]','["englisch","deutsch","geschichte"]','["sprachgewandt","analytisch","kommunikativ"]',0,0,0,0,0,0,32),
('Germanistik', 'Sprachen', 'Bachelor', 6, 'de', 0, NULL, 'Deutsche Sprache, Literatur und Medien.','Lehrer, Lektor, Journalist, Verlagswesen', '["sprachen","literatur","kultur","medien"]','["deutsch","englisch","geschichte"]','["textgewandt","analytisch","kommunikativ"]',0,0,0,0,0,0,42),
('Geschichte', 'Geisteswissenschaften', 'Bachelor', 6, 'de', 0, NULL, 'Vergangenheit analysieren, Quellenkritik, historische Zusammenhänge.','Archivar, Lehrer, Journalist, Museum', '["geschichte","kultur","politik","forschung"]','["geschichte","deutsch","englisch"]','["analytisch","recherchefreudig","detailorientiert"]',0,0,0,0,0,0,41),
('Philosophie', 'Geisteswissenschaften', 'Bachelor', 6, 'de', 0, NULL, 'Grundfragen von Wissen, Ethik, Logik und Existenz.','Journalist, Berater, Wissenschaft, Verwaltung', '["philosophie","logik","ethik","kultur"]','["deutsch","geschichte","englisch"]','["denkend","analytisch","diskursiv"]',0,0,0,0,0,0,58),
('Kunstgeschichte', 'Geisteswissenschaften', 'Bachelor', 6, 'de', 0, NULL, 'Kunstwerke und ihre historische Einordnung, Museen, Ausstellungen.','Museumskurator, Auktionator, Journalist', '["kunst","geschichte","kultur","reisen"]','["kunst","geschichte","deutsch"]','["visuell","analytisch","kulturell"]',0,0,0,0,1,0,53),

-- Teaching
('Lehramt Grundschule', 'Lehramt', 'Bachelor', 6, 'de', 1, 2.5, 'Ausbildung zur Grundschullehrkraft mit Fächern und Didaktik.','Grundschullehrer', '["mensch","bildung","gesellschaft","kreativ"]','["deutsch","mathematik","kunst"]','["geduldig","kommunikativ","organisiert"]',0,0,0,1,0,0,16),
('Lehramt Gymnasium Mathematik/Informatik', 'Lehramt', 'Bachelor', 6, 'de', 1, 2.3, 'Lehramt für Gymnasien mit den Fächern Mathematik und Informatik.','Gymnasiallehrer', '["bildung","technik","mathematik","mensch"]','["mathematik","informatik","physik"]','["erklaerend","geduldig","strukturiert"]',0,1,0,1,0,0,29),
('Lehramt Gymnasium Englisch/Deutsch', 'Lehramt', 'Bachelor', 6, 'de', 1, 2.4, 'Lehramt für Gymnasien mit den Fächern Englisch und Deutsch.','Gymnasiallehrer', '["bildung","sprachen","literatur","mensch"]','["englisch","deutsch","geschichte"]','["sprachgewandt","geduldig","kommunikativ"]',0,0,0,1,0,0,34),

-- Environment & Others
('Umweltwissenschaften', 'Umwelt', 'Bachelor', 6, 'de', 0, NULL, 'Natur- und Sozialwissenschaften für nachhaltige Umweltlösungen.','Umweltberater, Klimamanager, Naturschützer', '["umwelt","natur","forschung","gesellschaft"]','["biologie","chemie","geografie"]','["engagiert","analytisch","praktisch"]',0,1,0,1,0,0,44),
('Geografie', 'Umwelt', 'Bachelor', 6, 'de', 0, NULL, 'Räumliche Strukturen von Natur und Gesellschaft, Karten, Klima.','Raumplaner, Umweltberater, Geoinformatiker', '["natur","reisen","umwelt","gesellschaft"]','["geografie","mathematik","englisch"]','["analytisch","visuell","neugierig"]',0,1,0,0,0,0,39),
('Sportwissenschaft', 'Sport', 'Bachelor', 6, 'de', 1, 2.5, 'Bewegungswissenschaft, Training, Gesundheitssport, Sportmanagement.','Trainer, Sportmanager, Therapeut, Forscher', '["sport","gesundheit","mensch","management"]','["sport","biologie","mathematik"]','["praktisch","motivierend","teamfaehig"]',0,1,0,1,0,0,46),
('Tourismusmanagement', 'Wirtschaft', 'Bachelor', 6, 'de', 1, 2.6, 'Management von Reise, Hotels, Destinationen und Events.','Tourism Manager, Eventmanager, Hoteldirektor', '["reisen","wirtschaft","kultur","management"]','["englisch","geografie","deutsch"]','["kommunikativ","mobil","serviceorientiert"]',0,0,1,0,0,0,48),
('Game Design', 'Medien', 'Bachelor', 6, 'de', 1, 2.5, 'Konzeption, Design und Produktion von Computerspielen.','Game Designer, Level Designer, UX-Designer', '["spiele","design","technik","kreativ"]','["informatik","kunst","englisch"]','["kreativ","technisch","teamfaehig"]',0,1,0,0,1,0,37),
('Wirtschaftsingenieurwesen', 'Wirtschaft', 'Bachelor', 6, 'de', 1, 2.4, 'Verknüpfung von Ingenieurwissen und betriebswirtschaftlichem Denken.','Projektmanager, Berater, Produktionsleiter', '["technik","wirtschaft","management","logistik"]','["mathematik","physik","informatik"]','["analytisch","praktisch","unternehmerisch"]',0,1,1,0,0,0,10),
('Biomedical Engineering', 'Ingenieurwesen', 'Bachelor', 6, 'de/en', 1, 2.2, 'Entwicklung medizinischer Geräte, Prothesen und bildgebender Verfahren.','Medizintechniker, Forscher, Produktmanager', '["technik","medizin","forschung","innovation"]','["mathematik","physik","biologie"]','["interdisziplinaer","analytisch","innovativ"]',0,1,0,0,0,1,31),
('Aerospace Engineering', 'Ingenieurwesen', 'Bachelor', 6, 'en', 1, 2.1, 'Luft- und Raumfahrttechnik, Flugzeug- und Satellitenentwicklung.','Luft- und Raumfahrtingenieur, Forscher', '["technik","weltraum","forschung","innovation"]','["mathematik","physik","informatik"]','["analytisch","praezise","teamfaehig"]',0,1,0,0,0,0,47),
('Kognitionswissenschaft', 'Interdisziplinär', 'Bachelor', 6, 'de', 1, 2.2, 'Zusammenspiel von Psychologie, Informatik, Linguistik und Philosophie.','KI-Forscher, Usability-Experte, Berater', '["mensch","technik","sprachen","forschung"]','["informatik","biologie","mathematik"]','["interdisziplinaer","analytisch","neugierig"]',0,1,0,0,0,0,49),
('Public Health', 'Medizin & Gesundheit', 'Bachelor', 6, 'de', 1, 2.3, 'Gesundheit der Bevölkerung, Prävention, Gesundheitssysteme.','Gesundheitsmanager, Epidemiologe, Berater', '["gesundheit","gesellschaft","forschung","politik"]','["biologie","mathematik","sozialkunde"]','["analytisch","engagiert","strategisch"]',0,1,0,1,0,1,51),
('Ethnologie / Kulturwissenschaft', 'Geisteswissenschaften', 'Bachelor', 6, 'de', 0, NULL, 'Kulturen weltweit vergleichen, Feldarbeit, soziale Praktiken.','Kulturberater, Journalist, Museum, NGO', '["kultur","reisen","gesellschaft","forschung"]','["englisch","deutsch","geschichte"]','["offen","beobachtend","kommunikativ"]',0,0,0,1,0,0,57),
('Musikwissenschaft', 'Kunst', 'Bachelor', 6, 'de', 0, NULL, 'Historische und systematische Erforschung von Musik.','Musikjournalist, Kulturmanager, Lehrer', '["musik","kultur","geschichte","forschung"]','["musik","deutsch","englisch"]','["analytisch","musikalisch","detailorientiert"]',0,0,0,0,1,0,59),
('Theater-, Film- und Medienwissenschaft', 'Kunst', 'Bachelor', 6, 'de', 0, NULL, 'Analyse von Theater, Film und Medien als kulturelle Phänomene.','Kulturmanager, Dramaturg, Filmverleih, Journalist', '["film","theater","kultur","medien"]','["deutsch","englisch","kunst"]','["analytisch","kreativ","kommunikativ"]',0,0,0,0,1,0,52),
('Robotik / Autonome Systeme', 'Technik & IT', 'Bachelor', 6, 'de/en', 1, 2.0, 'Entwicklung intelligenter Roboter und automatisierter Systeme.','Robotik-Ingenieur, Forscher, Gründer', '["technik","roboter","ki","innovation"]','["mathematik","informatik","physik"]','["analytisch","praktisch","innovativ"]',0,1,0,0,0,0,43),
('Cybersecurity', 'Technik & IT', 'Bachelor', 6, 'de', 1, 2.2, 'Schutz von IT-Systemen, Netzwerke, Kryptografie, Ethical Hacking.','Security Analyst, Pentester, Security Architect', '["technik","sicherheit","logik","digitales"]','["informatik","mathematik","physik"]','["analytisch","vorsichtig","problemloesend"]',0,1,0,0,0,0,11);
